In [1]:
import pandas as pd

In [2]:
datas = pd.read_csv('../ml/arxiv_paper_preprocessed.csv')
datas

,Unnamed: 0,id,title,authors,abstract,published_date,category,url,last_updated,preprocessed_absract
0,0,2601.16953,Distribution of independent sets in perfect $r...,"Daniel Iľkovič, Jun Yan",given a graph g the family of all independent ...,[Submitted on 23 Jan 2026],Combinatorics (math.CO),https://arxiv.org/abs/2601.16953,2026-01-27 17:52:59.692787,"['given', 'a', 'graph', 'g', 'the', 'famili', ..."
1,1,2601.17818,ViTCoP: Accelerating Large Vision-Language Mod...,"Wen Luo, Peng Chen, Xiaotao Huang, LiQun Huang",large visionlanguage models lvlms incur high c...,[Submitted on 25 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.17818,2026-01-27 17:52:59.692787,"['larg', 'visionlanguag', 'model', 'lvlm', 'in..."
2,2,2601.17999,Application of log-Chebyshev approximation and...,Nikolai Krivulin,we consider multicriteria problems of evaluati...,[Submitted on 25 Jan 2026],Optimization and Control (math.OC),https://arxiv.org/abs/2601.17999,2026-01-27 17:52:59.692787,"['we', 'consid', 'multicriteria', 'problem', '..."
3,3,2601.17573,Weakly and Strongly Admissible Triplets for a ...,Abderrahman Bouhamidi,in this paper we investigate a class of collat...,[Submitted on 24 Jan 2026],General Mathematics (math.GM),https://arxiv.org/abs/2601.17573,2026-01-27 17:52:59.692787,"['in', 'thi', 'paper', 'we', 'investig', 'a', ..."
4,4,2601.18304,On the inclusion of bounded harmonic functions...,"Yair Hartman, Aranka Hrušková, Omer Segev",we investigate the conditions under which the ...,[Submitted on 26 Jan 2026],Probability (math.PR),https://arxiv.org/abs/2601.18304,2026-01-27 17:52:59.692787,"['we', 'investig', 'the', 'condit', 'under', '..."
...,...,...,...,...,...,...,...,...,...,...
1278,1278,2601.18303,Dicey Games: Shared Sources of Randomness in D...,"Léonard Brice, Thomas A. Henzinger, K. S. Thej...",consider a 4player version of matching pennies...,[Submitted on 26 Jan 2026],Computer Science and Game Theory (cs.GT),https://arxiv.org/abs/2601.18303,2026-01-27 17:52:59.692787,"['consid', 'a', '4player', 'version', 'of', 'm..."
1279,1279,2601.18513,LipNeXt: Scaling up Lipschitz-based Certified ...,"Kai Hu, Haoqi Hu, Matt Fredrikson",lipschitzbased certification offers efficient ...,[Submitted on 26 Jan 2026],Machine Learning (cs.LG),https://arxiv.org/abs/2601.18513,2026-01-27 17:52:59.692787,"['lipschitzbas', 'certif', 'offer', 'effici', ..."
1280,1280,2601.12441,The Dynamic and Endogenous Behavior of Re-Offe...,"Chuwen Zhang, Pengyi Shi, Amy Ward",incarcerationdiversion treatment programs aim ...,[Submitted on 18 Jan 2026],Computers and Society (cs.CY),https://arxiv.org/abs/2601.12441,2026-01-27 17:52:59.692787,"['incarcerationdivers', 'treatment', 'program'..."
1281,1281,2601.18240,V-Loop: Visual Logical Loop Verification for H...,"Mengyuan Jin, Zehui Liao, Yong Xia",multimodal large language models mllms have sh...,[Submitted on 26 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.18240,2026-01-27 17:52:59.692787,"['multimod', 'larg', 'languag', 'model', 'mllm..."
1282,1282,2601.16729,Derived equivalences for complexes with support,"K. Ganapathy, Sarang Sane",for a serre subcategory mathscr l and a resolv...,[Submitted on 23 Jan 2026],Category Theory (math.CT),https://arxiv.org/abs/2601.16729,2026-01-27 17:52:59.692787,"['for', 'a', 'serr', 'subcategori', 'mathscr',..."

In [3]:
datas

,Unnamed: 0,id,title,authors,abstract,published_date,category,url,last_updated,preprocessed_absract
0,0,2601.16953,Distribution of independent sets in perfect $r...,"Daniel Iľkovič, Jun Yan",given a graph g the family of all independent ...,[Submitted on 23 Jan 2026],Combinatorics (math.CO),https://arxiv.org/abs/2601.16953,2026-01-27 17:52:59.692787,"['given', 'a', 'graph', 'g', 'the', 'famili', ..."
1,1,2601.17818,ViTCoP: Accelerating Large Vision-Language Mod...,"Wen Luo, Peng Chen, Xiaotao Huang, LiQun Huang",large visionlanguage models lvlms incur high c...,[Submitted on 25 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.17818,2026-01-27 17:52:59.692787,"['larg', 'visionlanguag', 'model', 'lvlm', 'in..."
2,2,2601.17999,Application of log-Chebyshev approximation and...,Nikolai Krivulin,we consider multicriteria problems of evaluati...,[Submitted on 25 Jan 2026],Optimization and Control (math.OC),https://arxiv.org/abs/2601.17999,2026-01-27 17:52:59.692787,"['we', 'consid', 'multicriteria', 'problem', '..."
3,3,2601.17573,Weakly and Strongly Admissible Triplets for a ...,Abderrahman Bouhamidi,in this paper we investigate a class of collat...,[Submitted on 24 Jan 2026],General Mathematics (math.GM),https://arxiv.org/abs/2601.17573,2026-01-27 17:52:59.692787,"['in', 'thi', 'paper', 'we', 'investig', 'a', ..."
4,4,2601.18304,On the inclusion of bounded harmonic functions...,"Yair Hartman, Aranka Hrušková, Omer Segev",we investigate the conditions under which the ...,[Submitted on 26 Jan 2026],Probability (math.PR),https://arxiv.org/abs/2601.18304,2026-01-27 17:52:59.692787,"['we', 'investig', 'the', 'condit', 'under', '..."
...,...,...,...,...,...,...,...,...,...,...
1278,1278,2601.18303,Dicey Games: Shared Sources of Randomness in D...,"Léonard Brice, Thomas A. Henzinger, K. S. Thej...",consider a 4player version of matching pennies...,[Submitted on 26 Jan 2026],Computer Science and Game Theory (cs.GT),https://arxiv.org/abs/2601.18303,2026-01-27 17:52:59.692787,"['consid', 'a', '4player', 'version', 'of', 'm..."
1279,1279,2601.18513,LipNeXt: Scaling up Lipschitz-based Certified ...,"Kai Hu, Haoqi Hu, Matt Fredrikson",lipschitzbased certification offers efficient ...,[Submitted on 26 Jan 2026],Machine Learning (cs.LG),https://arxiv.org/abs/2601.18513,2026-01-27 17:52:59.692787,"['lipschitzbas', 'certif', 'offer', 'effici', ..."
1280,1280,2601.12441,The Dynamic and Endogenous Behavior of Re-Offe...,"Chuwen Zhang, Pengyi Shi, Amy Ward",incarcerationdiversion treatment programs aim ...,[Submitted on 18 Jan 2026],Computers and Society (cs.CY),https://arxiv.org/abs/2601.12441,2026-01-27 17:52:59.692787,"['incarcerationdivers', 'treatment', 'program'..."
1281,1281,2601.18240,V-Loop: Visual Logical Loop Verification for H...,"Mengyuan Jin, Zehui Liao, Yong Xia",multimodal large language models mllms have sh...,[Submitted on 26 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.18240,2026-01-27 17:52:59.692787,"['multimod', 'larg', 'languag', 'model', 'mllm..."
1282,1282,2601.16729,Derived equivalences for complexes with support,"K. Ganapathy, Sarang Sane",for a serre subcategory mathscr l and a resolv...,[Submitted on 23 Jan 2026],Category Theory (math.CT),https://arxiv.org/abs/2601.16729,2026-01-27 17:52:59.692787,"['for', 'a', 'serr', 'subcategori', 'mathscr',..."

In [4]:
datas['preprocessed_absract']

0       ['given', 'a', 'graph', 'g', 'the', 'famili', ...
1       ['larg', 'visionlanguag', 'model', 'lvlm', 'in...
2       ['we', 'consid', 'multicriteria', 'problem', '...
3       ['in', 'thi', 'paper', 'we', 'investig', 'a', ...
4       ['we', 'investig', 'the', 'condit', 'under', '...
                              ...
1278    ['consid', 'a', '4player', 'version', 'of', 'm...
1279    ['lipschitzbas', 'certif', 'offer', 'effici', ...
1280    ['incarcerationdivers', 'treatment', 'program'...
1281    ['multimod', 'larg', 'languag', 'model', 'mllm...
1282    ['for', 'a', 'serr', 'subcategori', 'mathscr',...
Name: preprocessed_absract, Length: 1283, dtype: object

In [5]:
vectorized_df = datas[['preprocessed_absract']].copy()
vectorized_df

                                   preprocessed_absract
0     ['given', 'a', 'graph', 'g', 'the', 'famili', ...
1     ['larg', 'visionlanguag', 'model', 'lvlm', 'in...
2     ['we', 'consid', 'multicriteria', 'problem', '...
3     ['in', 'thi', 'paper', 'we', 'investig', 'a', ...
4     ['we', 'investig', 'the', 'condit', 'under', '...
...                                                 ...
1278  ['consid', 'a', '4player', 'version', 'of', 'm...
1279  ['lipschitzbas', 'certif', 'offer', 'effici', ...
1280  ['incarcerationdivers', 'treatment', 'program'...
1281  ['multimod', 'larg', 'languag', 'model', 'mllm...
1282  ['for', 'a', 'serr', 'subcategori', 'mathscr',...

[1283 rows x 1 columns]

In [6]:
datas.drop(columns=['preprocessed_absract'], inplace=True)

In [7]:
from collections import Counter


# # column name in the dataframe is 'preprocessed_absract' (typo), use that
# datas['tf'] = datas['preprocessed_absract'].apply(Counter)

In [8]:
datas

,Unnamed: 0,id,title,authors,abstract,published_date,category,url,last_updated
0,0,2601.16953,Distribution of independent sets in perfect $r...,"Daniel Iľkovič, Jun Yan",given a graph g the family of all independent ...,[Submitted on 23 Jan 2026],Combinatorics (math.CO),https://arxiv.org/abs/2601.16953,2026-01-27 17:52:59.692787
1,1,2601.17818,ViTCoP: Accelerating Large Vision-Language Mod...,"Wen Luo, Peng Chen, Xiaotao Huang, LiQun Huang",large visionlanguage models lvlms incur high c...,[Submitted on 25 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.17818,2026-01-27 17:52:59.692787
2,2,2601.17999,Application of log-Chebyshev approximation and...,Nikolai Krivulin,we consider multicriteria problems of evaluati...,[Submitted on 25 Jan 2026],Optimization and Control (math.OC),https://arxiv.org/abs/2601.17999,2026-01-27 17:52:59.692787
3,3,2601.17573,Weakly and Strongly Admissible Triplets for a ...,Abderrahman Bouhamidi,in this paper we investigate a class of collat...,[Submitted on 24 Jan 2026],General Mathematics (math.GM),https://arxiv.org/abs/2601.17573,2026-01-27 17:52:59.692787
4,4,2601.18304,On the inclusion of bounded harmonic functions...,"Yair Hartman, Aranka Hrušková, Omer Segev",we investigate the conditions under which the ...,[Submitted on 26 Jan 2026],Probability (math.PR),https://arxiv.org/abs/2601.18304,2026-01-27 17:52:59.692787
...,...,...,...,...,...,...,...,...,...
1278,1278,2601.18303,Dicey Games: Shared Sources of Randomness in D...,"Léonard Brice, Thomas A. Henzinger, K. S. Thej...",consider a 4player version of matching pennies...,[Submitted on 26 Jan 2026],Computer Science and Game Theory (cs.GT),https://arxiv.org/abs/2601.18303,2026-01-27 17:52:59.692787
1279,1279,2601.18513,LipNeXt: Scaling up Lipschitz-based Certified ...,"Kai Hu, Haoqi Hu, Matt Fredrikson",lipschitzbased certification offers efficient ...,[Submitted on 26 Jan 2026],Machine Learning (cs.LG),https://arxiv.org/abs/2601.18513,2026-01-27 17:52:59.692787
1280,1280,2601.12441,The Dynamic and Endogenous Behavior of Re-Offe...,"Chuwen Zhang, Pengyi Shi, Amy Ward",incarcerationdiversion treatment programs aim ...,[Submitted on 18 Jan 2026],Computers and Society (cs.CY),https://arxiv.org/abs/2601.12441,2026-01-27 17:52:59.692787
1281,1281,2601.18240,V-Loop: Visual Logical Loop Verification for H...,"Mengyuan Jin, Zehui Liao, Yong Xia",multimodal large language models mllms have sh...,[Submitted on 26 Jan 2026],Computer Vision and Pattern Recognition (cs.CV),https://arxiv.org/abs/2601.18240,2026-01-27 17:52:59.692787
1282,1282,2601.16729,Derived equivalences for complexes with support,"K. Ganapathy, Sarang Sane",for a serre subcategory mathscr l and a resolv...,[Submitted on 23 Jan 2026],Category Theory (math.CT),https://arxiv.org/abs/2601.16729,2026-01-27 17:52:59.692787

In [9]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf_vectorizer = TfidfVectorizer()

tfidf_matrix = tfidf_vectorizer.fit_transform(
    vectorized_df['preprocessed_absract']
)

In [10]:
print(tfidf_matrix.shape)
print(tfidf_vectorizer.get_feature_names_out()[:20])

(1283, 13503)
['0001' '0036' '006' '00870295' '01' '010' '011' '0118mpa' '0128' '015'
 '01k' '0203' '025' '025021' '02664' '0289' '031' '032' '0329' '0336']

In [11]:
import numpy as np
import pandas as pd

feature_names = tfidf_vectorizer.get_feature_names_out()


tfidf_global = tfidf_matrix.sum(axis=0)  # type: ignore # shape: (1, n_features)

tfidf_values = np.asarray(tfidf_global).flatten()

tfidf_df = pd.DataFrame({
    "term": feature_names,
    "tfidf": tfidf_values
}).sort_values(by="tfidf", ascending=False)

tfidf_df.head(1283)

          term       tfidf
12085      the  146.886436
1111       and   95.000990
8484        of   93.558226
12251       to   65.143853
5782        in   57.469420
...        ...         ...
4064     euler    1.553704
5520   horizon    1.552822
10074   recurr    1.548689
5671      idea    1.544534
11831   tailor    1.540355

[1283 rows x 2 columns]

In [12]:
from sklearn.metrics.pairwise import cosine_similarity


cosine_sim_matrix = cosine_similarity(tfidf_matrix, tfidf_matrix)



cosine_sim_df = pd.DataFrame(
    cosine_sim_matrix, 
    index=[f"Doc {i}" for i in range(tfidf_matrix.shape[0])],
    columns=[f"Doc {i}" for i in range(tfidf_matrix.shape[0])]
)


print("Matriks Cosine Similarity (Sampel):")
print(cosine_sim_df.iloc[:20, :20])

Matriks Cosine Similarity (Sampel):
           Doc 0     Doc 1     Doc 2     Doc 3     Doc 4     Doc 5     Doc 6  \
Doc 0   1.000000  0.049307  0.117027  0.121875  0.083296  0.035747  0.071637
Doc 1   0.049307  1.000000  0.077005  0.058818  0.059826  0.081031  0.072403
Doc 2   0.117027  0.077005  1.000000  0.146179  0.110241  0.069106  0.189242
Doc 3   0.121875  0.058818  0.146179  1.000000  0.069920  0.035051  0.093924
Doc 4   0.083296  0.059826  0.110241  0.069920  1.000000  0.040404  0.088540
Doc 5   0.035747  0.081031  0.069106  0.035051  0.040404  1.000000  0.042042
Doc 6   0.071637  0.072403  0.189242  0.093924  0.088540  0.042042  1.000000
Doc 7   0.102367  0.068716  0.203767  0.066952  0.092319  0.025839  0.181192
Doc 8   0.045410  0.122171  0.076960  0.062030  0.041485  0.152470  0.053045
Doc 9   0.063892  0.043090  0.200363  0.100591  0.099969  0.025883  0.109976
Doc 10  0.071526  0.111384  0.091474  0.060501  0.049533  0.044096  0.057659
Doc 11  0.053655  0.074167  0.071586  0.041520  0.036212  0.034041  0.062800
Doc 12  0.088340  0.057661  0.183173  0.115786  0.063715  0.049581  0.119030
Doc 13  0.088207  0.063582  0.142331  0.096137  0.094173  0.035137  0.131740
Doc 14  0.075926  0.103396  0.151032  0.147120  0.055635  0.034413  0.132230
Doc 15  0.083255  0.093430  0.178707  0.112847  0.110468  0.039206  0.116450
Doc 16  0.056845  0.104318  0.064357  0.041072  0.035751  0.028905  0.046885
Doc 17  0.060720  0.096084  0.091602  0.063138  0.045727  0.072651  0.056072
Doc 18  0.040992  0.149956  0.051825  0.064925  0.034742  0.056933  0.035161
Doc 19  0.059138  0.044859  0.113997  0.080830  0.073206  0.017614  0.084038

           Doc 7     Doc 8     Doc 9    Doc 10    Doc 11    Doc 12    Doc 13  \
Doc 0   0.102367  0.045410  0.063892  0.071526  0.053655  0.088340  0.088207
Doc 1   0.068716  0.122171  0.043090  0.111384  0.074167  0.057661  0.063582
Doc 2   0.203767  0.076960  0.200363  0.091474  0.071586  0.183173  0.142331
Doc 3   0.066952  0.062030  0.100591  0.060501  0.041520  0.115786  0.096137
Doc 4   0.092319  0.041485  0.099969  0.049533  0.036212  0.063715  0.094173
Doc 5   0.025839  0.152470  0.025883  0.044096  0.034041  0.049581  0.035137
Doc 6   0.181192  0.053045  0.109976  0.057659  0.062800  0.119030  0.131740
Doc 7   1.000000  0.051322  0.091167  0.079118  0.050550  0.094127  0.125950
Doc 8   0.051322  1.000000  0.036697  0.100043  0.059746  0.042651  0.060581
Doc 9   0.091167  0.036697  1.000000  0.054830  0.039991  0.148814  0.126482
Doc 10  0.079118  0.100043  0.054830  1.000000  0.062129  0.073062  0.057053
Doc 11  0.050550  0.059746  0.039991  0.062129  1.000000  0.047695  0.069848
Doc 12  0.094127  0.042651  0.148814  0.073062  0.047695  1.000000  0.125447
Doc 13  0.125950  0.060581  0.126482  0.057053  0.069848  0.125447  1.000000
Doc 14  0.085774  0.068163  0.089592  0.074580  0.055190  0.095131  0.118432
Doc 15  0.127281  0.068508  0.123156  0.111612  0.062232  0.090106  0.136853
Doc 16  0.065154  0.038689  0.036708  0.072129  0.047495  0.036728  0.041708
Doc 17  0.058814  0.078755  0.042941  0.087675  0.056099  0.040614  0.052061
Doc 18  0.051702  0.051643  0.037219  0.059663  0.034858  0.028123  0.038958
Doc 19  0.063724  0.042956  0.064421  0.041651  0.034854  0.056120  0.058190

          Doc 14    Doc 15    Doc 16    Doc 17    Doc 18    Doc 19
Doc 0   0.075926  0.083255  0.056845  0.060720  0.040992  0.059138
Doc 1   0.103396  0.093430  0.104318  0.096084  0.149956  0.044859
Doc 2   0.151032  0.178707  0.064357  0.091602  0.051825  0.113997
Doc 3   0.147120  0.112847  0.041072  0.063138  0.064925  0.080830
Doc 4   0.055635  0.110468  0.035751  0.045727  0.034742  0.073206
Doc 5   0.034413  0.039206  0.028905  0.072651  0.056933  0.017614
Doc 6   0.132230  0.116450  0.046885  0.056072  0.035161  0.084038
Doc 7   0.085774  0.127281  0.065154  0.058814  0.051702  0.063724
Doc 8   0.068163  0.068508  0.038689  0.078755  0.051643  0.042956
Doc 9   0.089592  0.123156  0.036708  0.042941  0.037219  0.064421
Doc 10  0.074580  0.111612  0.072129  0.087675  0.059663  0.041651
Doc 11  0.055190  0.062232  0.047495  0.056099  0.034858  0.034854
Doc 12  0.095131  0.090106  0.036728  0.040614  0.028123  0.056120
Doc 13  0.118432  0.136853  0.041708  0.052061  0.038958  0.058190
Doc 14  1.000000  0.127743  0.048842  0.046735  0.042338  0.041256
Doc 15  0.127743  1.000000  0.047096  0.083208  0.076870  0.079260
Doc 16  0.048842  0.047096  1.000000  0.037014  0.051339  0.024205
Doc 17  0.046735  0.083208  0.037014  1.000000  0.120154  0.057084
Doc 18  0.042338  0.076870  0.051339  0.120154  1.000000  0.037544
Doc 19  0.041256  0.079260  0.024205  0.057084  0.037544  1.000000

In [13]:
for i in range(10): 
    sims = cosine_sim_matrix[i]
    top_indices = sims.argsort()[::-1][1:6]
    
    print(f"\nDoc {i} paling mirip dengan:")
    for idx in top_indices:
        print(f"  -> Doc {idx} (score: {sims[idx]:.3f})")

Doc 0 paling mirip dengan:
  -> Doc 733 (score: 0.253)
  -> Doc 115 (score: 0.234)
  -> Doc 1259 (score: 0.232)
  -> Doc 1013 (score: 0.221)
  -> Doc 952 (score: 0.214)

Doc 1 paling mirip dengan:
  -> Doc 133 (score: 0.402)
  -> Doc 1039 (score: 0.305)
  -> Doc 1209 (score: 0.267)
  -> Doc 188 (score: 0.261)
  -> Doc 758 (score: 0.239)

Doc 2 paling mirip dengan:
  -> Doc 889 (score: 0.337)
  -> Doc 146 (score: 0.286)
  -> Doc 1162 (score: 0.284)
  -> Doc 1220 (score: 0.281)
  -> Doc 432 (score: 0.279)

Doc 3 paling mirip dengan:
  -> Doc 1267 (score: 0.181)
  -> Doc 733 (score: 0.177)
  -> Doc 742 (score: 0.168)
  -> Doc 336 (score: 0.165)
  -> Doc 432 (score: 0.164)

Doc 4 paling mirip dengan:
  -> Doc 977 (score: 0.217)
  -> Doc 843 (score: 0.204)
  -> Doc 1172 (score: 0.177)
  -> Doc 865 (score: 0.173)
  -> Doc 404 (score: 0.165)

Doc 5 paling mirip dengan:
  -> Doc 263 (score: 0.161)
  -> Doc 249 (score: 0.161)
  -> Doc 108 (score: 0.160)
  -> Doc 8 (score: 0.152)
  -> Doc 978 (score: 0.141)

Doc 6 paling mirip dengan:
  -> Doc 675 (score: 0.315)
  -> Doc 872 (score: 0.249)
  -> Doc 1137 (score: 0.234)
  -> Doc 893 (score: 0.216)
  -> Doc 1226 (score: 0.215)

Doc 7 paling mirip dengan:
  -> Doc 936 (score: 0.255)
  -> Doc 977 (score: 0.255)
  -> Doc 1137 (score: 0.251)
  -> Doc 811 (score: 0.228)
  -> Doc 1070 (score: 0.218)

Doc 8 paling mirip dengan:
  -> Doc 108 (score: 0.270)
  -> Doc 758 (score: 0.216)
  -> Doc 249 (score: 0.185)
  -> Doc 1233 (score: 0.182)
  -> Doc 1247 (score: 0.174)

Doc 9 paling mirip dengan:
  -> Doc 617 (score: 0.269)
  -> Doc 1190 (score: 0.202)
  -> Doc 2 (score: 0.200)
  -> Doc 790 (score: 0.189)
  -> Doc 344 (score: 0.189)

In [ ]:
from cbf import ContentBasedFiltering


cbf = ContentBasedFiltering(datas, tfidf_vectorizer, tfidf_matrix)

input_abstract = datas['abstract'][10]
recommendations = cbf.get_recommendations_by_abstract(
    input_abstract,
    top_n=100
)

In [16]:
recommendations

                                                Title  Similarity Score
0   TechING: Towards Real World Technical Image Un...          0.758130
1   Designing large language model prompts to extr...          0.146503
2   Collective intelligence in science: direct eli...          0.133545
3   Inference from high-frequency data: A subsampl...          0.129586
4   Corpus-Based Approaches to Igbo Diacritic Rest...          0.129560
..                                                ...               ...
95  Contrasting Global and Patient-Specific Regres...          0.092118
96  ShapLoRA: Allocation of Low-rank Adaption on L...          0.092057
97  On positivity of CM line bundles on the moduli...          0.091828
98  Reevaluating Causal Estimation Methods with Da...          0.091691
99          Large Coupling Limits Beyond Definiteness          0.091431

[100 rows x 2 columns]

In [17]:
datas.to_csv('arxiv_recap.csv', index=False)